### ISSUE TITLE
unable to install in Catalina's final release

### ISSUE THREAD

**Issue by ColeMacGrath** [chris1111/WIFI-Dlink-Catalina-Panel-V2#2]
Is not possible to install in final release of Catalina, macOS installer says: package not compatible with this macOS version

**Comment by ColeMacGrath** [comment]
It's works following this:
* Shutdown
* Hold command+R and press power (or recovery mode in clover)
* Launch terminal
* csrutil disable
* Reboot
* Launch terminal
* mount -uw /
* Run the installer
* Shutdown
* Hold command+R and press power (or recovery mode in clover)
* Launch terminal
* csrutil enable
* Reboot

**Comment by chris1111** [comment]
Program Update
You have to disable the first utility with the first program
Use the V2 update
