### ISSUE TITLE
why not share the actual code

### ISSUE THREAD

**Issue by moda20** [chris1111/WIFI-Dlink-Catalina-Panel-V2#4]
why not share the actual code, so someone will actually work the integration into the wireless utility of macOs not with a new utility that has less than perfect UI.

**Comment by chris1111** [comment]
where do you see a code of that?

**Comment by moda20** [comment]
I am asking you to share the code of the widget you made.

**Comment by chris1111** [comment]
> I am asking you to share the code of the widget you made.

Its not a widget it a D-Link utility old of 8 years
