### ISSUE TITLE
Sleep/Wakeup 

### ISSUE THREAD

**Issue by ForresterAlex** [chris1111/WIFI-Dlink-Catalina-Panel-V2#7]
Driver does not reconize hardware after sleeping and waking up again. You closed an issue related to this a while back without a solution, is there one?

**Comment by Cass67** [comment]
Seems to be OK with this one:

https://github.com/chris1111/Wireless-Ralink-Panel-Utility

Create a profile in the wireless tool 
sleep / wake
connects to wifi after about 10 secs

**Comment by ForresterAlex** [comment]
Thanks, I would test, but I broke my wifi dongle by sitting on it, I may test it if I get around to fixing the USB port.
